### ISSUE TITLE
Lightcurve generation using binned likelihood in quickCurve

### ISSUE THREAD

**Issue by astro-fermi** [kialio/LATAnalysisScripts#14]
Dear Sir,

Is it possible to generate light curve using binned likelihood method in quickCurve?

I gave 'binned = True' option in _2FGLJ0217.7+7353.cfg file. After that, when I ran following command-
'quickCurve run _2FGLJ0217.7+7353'

it generated only those files which are used in unbinned analysis (ltcube & expMap) and not  those which are used for binned analysis (srcMaps). Therefore, when I ran next command-
quickCurve compute _2FGLJ0217.7+7353
following error appeared
IOError: SourceMaps file not found.

I checked the quickCurve.py script and I found that though there is an option of doing binned likelihood fitting, but it generate files only for unbinned likelihood (line number 109 to 120).

I request you to kindly take a look of the issue.
Thank you very much.

-- Vaidehi

**Comment by kialio** [comment]
Hi,

The binned method isn't working right now.

J.

**Comment by kialio** [comment]
Thanks to @jefemagril binned analysis now works in quickCurve.
