### ISSUE TITLE
removeWeak problem

### ISSUE THREAD

**Issue by tinitus74** [kialio/LATAnalysisScripts#7]
Hi, when I try to remove weak sources from the fit I get the following error message: 

File "/home/clementina/Fermi/ScienceTools-v9r31p1-fssc-20130410-x86_64-unknown-linux-gnu-libc2.12/x86_64-unknown-linux-gnu-libc2.12/lib/python2.7/site-packages/quickLike.py", line 491, in removeWeak
    if(self.MIN.freePars(name).size() > 0):
AttributeError: 'tuple' object has no attribute 'size

What would be the problem? 
Thanks

**Comment by kialio** [comment]
Hi,

It looks like you are using an old version of the scripts.  I fixed this bug at some point in the past.  You can download a version from github here or from the FSSC User Contributed Tools site.  Let me know if you need anything else.

Jeremy
